import React from "react";
export const metadata = {
  title: "About The Web",
  description: "Generated by create next app",
};

function page() {
  return (
    <div>
      <h1>About</h1>
      <p>
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illum optio
        porro, dolores accusamus officiis doloribus? Eveniet earum eligendi
        sunt, explicabo impedit dolore, praesentium perferendis eum, officiis
        sint tempore fugit! Laboriosam, minima aut, nam quidem error sed qui
        excepturi, animi fugit fugiat quod obcaecati. Autem quae tempore magni
        repudiandae dicta consequuntur!
      </p>
    </div>
  );
}

export default page;
