import React from "react";
export const metadata = {
  title: "Our Web Team",
  description: "Generated by create next app",
};

function page() {
  return (
    <div>
      <h1>Our Team</h1>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, delectus
        culpa. Nesciunt nisi sapiente beatae facere consequatur ad incidunt
        error, neque repudiandae quibusdam ratione tempore quidem distinctio
        omnis non necessitatibus quod ab veniam maxime eligendi recusandae
        numquam! Corporis officiis earum, doloremque amet omnis quis voluptates!
        Officia id eaque cum saepe.
      </p>
    </div>
  );
}

export default page;
